plugins {
    id("io.micronaut.build.internal.servlet.implementation")
}

dependencies {
    implementation libs.tomcat.embed.core
    testImplementation libs.bcpkix
    testImplementation(mnSerde.micronaut.serde.jackson)
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testImplementation(projects.micronautServletWebsocket)
    testImplementation libs.tomcat.embed.websocket
}

