To use https://www.eclipse.org/jetty/[Jetty] as a server add the following dependency:

dependency:io.micronaut.servlet:micronaut-http-server-jetty[]

NOTE: Jetty is supported with GraalVM native image

NOTE: If you plan to produce a WAR file then the dependency should be `developmentOnly`.

To customize the Jetty server you can use the following configuration properties:

include::{includedir}configurationProperties/io.micronaut.servlet.jetty.JettyConfiguration.adoc[]

To disable the Jetty runtime when it is present on the classpath:

[configuration]
----
micronaut.server.jetty.enabled: false
----

This is useful when multiple servlet runtimes are available and you want Micronaut to ignore Jetty during startup.

Or you can register a `BeanCreatedEventListener`:

.Jetty Server Customization
[source,java]
----
include::http-server-jetty/src/test/java/io/micronaut/servlet/jetty/docs/JettyServerCustomizer.java[tags=imports, indent=0]

include::http-server-jetty/src/test/java/io/micronaut/servlet/jetty/docs/JettyServerCustomizer.java[tags=class, indent=0]
----

=== Static Resources

Static resources configured with `micronaut.router.static-resources` are served by the Micronaut static resource resolver, as on the other runtimes, so filters, CORS and the `micronaut.server.responses.file` settings apply to them. To have Jetty's own `ResourceHandler` serve them instead, which supports range requests natively but bypasses the Micronaut filter chain, set:

[configuration]
----
micronaut.server.jetty.native-static-resources: true
----

=== Access Log Configuration

To configure the https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-http-request-logging[Jetty Access Log]:

.Jetty Access Log Configuration
[configuration]
----
micronaut.server.jetty.access-log.enabled: true
micronaut.server.jetty.access-log.filename: /tmp/access.log
micronaut.server.jetty.access-log.retain-days: 10
micronaut.server.jetty.access-log.pattern: >
    %{client}a - %u %t "%r" %s %O
----

== Jetty support for https://logback.qos.ch/access.html[Logback access]

If you want to use https://logback.qos.ch/access.html[Logback access] library with jetty you have to provide logback dependency on classpath:

dependency:ch.qos.logback.access:logback-access-common[]

By default, it will check for logback-access.xml in resources folder.
