There are some known issues with Servlet integration to the Micronaut Framework

=== HttpProxyClient and Server Filters

It is not currently possible to use the HttpProxyClient with Servlet Filters.

=== Error handlers re-reading the request body

Local error handlers that require the request body to be reparsed will not work in Servlet based applications.
The body is read from the request input-stream and so attempting to reparse it for the error handler will fail.

=== Management port

With a Netty based server, you can https://docs.micronaut.io/latest/guide/#_management_port[configure a management port for the server].
This is not currently supported with Servlet based servers, and management endpoints (when enabled) will be available on the same port as the main application.

=== ServiceReadyEvent publication

When using the Netty runtime, the `ServiceReadyEvent` is automatically published when the server is ready to accept requests.
This is not currently supported with Servlet based servers.

If you wish to generate a `ServiceReadyEvent` you can do so manually by injecting a `ApplicationEventPublisher<ServiceReadyEvent>` bean and publishing the event yourself when your application is ready.
