plugins {
    id 'io.micronaut.build.internal.servlet.base'
    id 'io.micronaut.build.internal.module'
}
ossIndexAudit {
    excludeCoordinates = [
            "io.undertow:undertow-core:2.3.24.Final" // no patched version https://ossindex.sonatype.org/component/pkg:maven/io.undertow/undertow-core
    ]
}
