plugins {
    id 'io.micronaut.build.internal.servlet.base'
    id 'io.micronaut.build.internal.module'
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = "25"
    targetCompatibility = "25"
}

tasks.withType(GroovyCompile).configureEach {
    sourceCompatibility = "25"
    targetCompatibility = "25"
}

ossIndexAudit {
    excludeCoordinates = [
            "io.undertow:undertow-core:2.4.1.Final" // no patched version https://ossindex.sonatype.org/component/pkg:maven/io.undertow/undertow-core
    ]
}
