plugins {
    id "io.micronaut.build.internal.parent"
}

repositories {
    mavenCentral()
    maven {
        url = "https://central.sonatype.com/repository/maven-snapshots/"
        mavenContent { snapshotsOnly() }
    }
}
configurations.all {
    resolutionStrategy {
        preferProjectModules()
    }
}
