[versions]
micronaut = "5.2.13"
managed-servlet-api = '6.1.0'
managed-jakarta-websocket-api = '2.2.0'
kotest-runner = '6.2.5'
undertow = '2.3.26.Final'
tomcat = '11.0.26'
bcpkix = "1.86"

managed-apache-http-core5 = "5.4.4"
managed-jetty = '12.1.13'
micronaut-reactor = "4.3.0"
micronaut-security = "5.4.0"
micronaut-serde = "3.2.4"
micronaut-session = "5.2.0"
micronaut-validation = "5.2.1"
micronaut-logging = "2.1.0"
# Micronaut
micronaut-gradle-plugin = "5.0.2"
logback-access = "2.0.15"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

boms-jetty = { module = 'org.eclipse.jetty:jetty-bom', version.ref = 'managed-jetty' }

managed-servlet-api = { module = 'jakarta.servlet:jakarta.servlet-api', version.ref = 'managed-servlet-api' }
managed-jakarta-websocket-api = '2.2.0'
managed-jakarta-websocket-client-api = { module = 'jakarta.websocket:jakarta.websocket-client-api', version.ref = 'managed-jakarta-websocket-api' }

micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
micronaut-reactor = "4.3.0"
micronaut-security = "5.4.0"
micronaut-serde = "3.2.4"
micronaut-session = "5.2.0"
micronaut-validation = "5.2.1"

junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine" }
kotlin-stdlib-jdk8 = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8' }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect' }

apache-http-core5 = { module = 'org.apache.httpcomponents.core5:httpcore5', version.ref = 'managed-apache-http-core5' }
tomcat-embed-core = { module = 'org.apache.tomcat.embed:tomcat-embed-core', version.ref = 'tomcat' }
tomcat-embed-websocket = { module = 'org.apache.tomcat.embed:tomcat-embed-websocket', version.ref = 'tomcat' }
undertow-servlet = { module = 'io.undertow:undertow-servlet', version.ref = 'undertow' }
undertow-websockets-jsr = { module = 'io.undertow:undertow-websockets-jsr', version.ref = 'undertow' }
jetty-servlet = { module = 'org.eclipse.jetty.ee10:jetty-ee10-servlet', version.ref = 'managed-jetty' }
jetty-websocket-jakarta-server = { module = 'org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-server', version.ref = 'managed-jetty' }
jetty-http2-server = { module = 'org.eclipse.jetty.http2:jetty-http2-server', version.ref = 'managed-jetty' }
jetty-alpn-server = { module = 'org.eclipse.jetty:jetty-alpn-server', version.ref = 'managed-jetty' }
jetty-alpn-java-server = { module = 'org.eclipse.jetty:jetty-alpn-java-server', version.ref = 'managed-jetty' }
jetty-alpn-conscrypt-server = { module = 'org.eclipse.jetty:jetty-alpn-conscrypt-server', version.ref = 'managed-jetty' }
kotest-runner = '6.2.5'
bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix" }
logback-access-jetty12 = { module = "ch.qos.logback.access:logback-access-jetty12", version.ref = "logback-access" }

# Gradle
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
