In a standalone Micronaut Framework application, https://docs.micronaut.io/latest/guide/#propertySource[external property sources for configuration] can be configured via the Java system property `micronaut.config.files` or the environment variable `MICRONAUT_CONFIG_FILES`.
When running as a WAR file, this can be problematic if you wish to run multiple Micronaut Framework WARs in the same container, as all applications will share the same location.

To allow an external location per application, it is necessary to write our own replacement for api:servlet.engine.initializer.MicronautServletInitializer[].
The following example will look for configuration in the `/tmp` directory and on the classpath in the `/some/path` directory.

snippet::io.micronaut.servlet.docs.war.CustomInitializer[tags="class", indent=0, languages="java,kotlin,groovy"]

[.lang-python]
NOTE: The servlet container instantiates the initializer itself, before any application context and therefore before the Python runtime exists, and a Python class cannot extend the Java class `MicronautServletInitializer`. Write the initializer in Java, Kotlin or Groovy as shown above; the application it starts can be written in Python.

We can then use Java's Service Provider Interface to register this class as the initializer by pointing to it in the `META-INF/services/jakarta.servlet.ServletContainerInitializer` file.

[source,text]
.src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
----
io.micronaut.servlet.docs.war.CustomInitializer
----

NOTE: Some servlet containers may limit the locations that are accessible from applications for security reasons.
